M48
; DRILL file {KiCad 8.0.6-8.0.6-0~ubuntu20.04.1} date 2024-12-12T22:35:06+0500
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-12-12T22:35:06+05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.6-8.0.6-0~ubuntu20.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.500
%
G90
G05
T1
X276.695Y-101.61
X276.695Y-107.39
T2
X231.737Y-84.5
X235.737Y-84.5
M30
